### ISSUE TITLE
\n newline characters no longer work properly with TeX Math Here

### ISSUE THREAD

**Issue by dtserban** [mathaddons/tex-math-here#8]
I suspect it is the method of data transport from user to server that is not accounting for this.
![image](https://user-images.githubusercontent.com/54650186/79842539-f6576380-8386-11ea-9f07-b85132a8f68a.png)

**Comment by npjg** [comment]
This was an issue with URL encoding and filtering newlines and tabs. It has been resolved in the latest master.
